wandb_version: 1

algorithm:
  value: dueling_dqn
batch_size:
  value: 128
buffer_size:
  value: 100
env:
  value: cartpole
learning_rate:
  value: 0.001515489729744819
update_period:
  value: 2
use_baseline:
  value: false
