_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-x86_64
algorithm:
    value: mc_reinforce
batch_size:
    value: 128
buffer_size:
    value: 100000
env:
    value: acrobot
gamma:
    value: 0.99
learning_rate:
    value: 0.001
sweep_id:
    value: null
update_period:
    value: 4
use_baseline:
    value: false
use_max:
    value: false
value_learning_rate:
    value: 0.001
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: rl-pa2
wandb_sweep:
    value: false
